import { serve } from 'https://deno.land/std@0.208.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL              = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

interface HRAPayload {
  paymentId: string;
}

// Generates a plain-text HRA rent receipt
// In production replace with a PDF generation library (e.g. pdfkit)
const buildReceiptHtml = (data: {
  tenantName: string;
  tenantPan?: string;
  landlordName: string;
  landlordPan?: string;
  propertyAddress: string;
  month: string;
  amount: number;
  receiptNo: string;
  paidAt: string;
}): string => `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Rent Receipt</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 600px; margin: 40px auto; color: #1a1a1a; }
  h1 { font-size: 20px; text-align: center; }
  .label { color: #666; font-size: 12px; text-transform: uppercase; }
  .value { font-weight: bold; font-size: 14px; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  td { padding: 8px 0; border-bottom: 1px solid #eee; }
  .amount { font-size: 24px; font-weight: bold; color: #1A56FF; }
  .footer { margin-top: 40px; font-size: 11px; color: #999; text-align: center; }
</style>
</head>
<body>
  <h1>RENT RECEIPT</h1>
  <p style="text-align:center">Receipt No: <strong>${data.receiptNo}</strong></p>
  <p class="amount" style="text-align:center">₹${data.amount.toLocaleString('en-IN')}</p>
  <table>
    <tr><td class="label">Received From</td><td class="value">${data.tenantName}${data.tenantPan ? ` (PAN: ${data.tenantPan})` : ''}</td></tr>
    <tr><td class="label">Paid To</td><td class="value">${data.landlordName}${data.landlordPan ? ` (PAN: ${data.landlordPan})` : ''}</td></tr>
    <tr><td class="label">Property</td><td class="value">${data.propertyAddress}</td></tr>
    <tr><td class="label">Rent Month</td><td class="value">${data.month}</td></tr>
    <tr><td class="label">Payment Date</td><td class="value">${data.paidAt}</td></tr>
    <tr><td class="label">Amount</td><td class="value">₹${data.amount.toLocaleString('en-IN')} (Rupees only)</td></tr>
  </table>
  <p>I, <strong>${data.landlordName}</strong>, hereby acknowledge receipt of the above amount as rent for the above-mentioned property.</p>
  <p style="margin-top: 40px;">________________________<br><strong>${data.landlordName}</strong><br>Landlord Signature</p>
  <div class="footer">Generated by Flatvio · flatvio.in · This is a computer-generated receipt.</div>
</body>
</html>
`;

serve(async (req) => {
  if (req.method !== 'POST') {
    return new Response('Method Not Allowed', { status: 405 });
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

  try {
    const { paymentId }: HRAPayload = await req.json();

    if (!paymentId) {
      return new Response(JSON.stringify({ error: 'paymentId required' }), { status: 400 });
    }

    // Fetch payment with joined rental and profiles
    const { data: payment, error } = await supabase
      .from('rent_payments')
      .select(`
        *,
        rental:rentals(
          *,
          property:properties(*),
          landlord:profiles!rentals_landlord_id_fkey(*),
          tenant:profiles!rentals_tenant_id_fkey(*)
        )
      `)
      .eq('id', paymentId)
      .single();

    if (error || !payment) {
      return new Response(JSON.stringify({ error: 'Payment not found' }), { status: 404 });
    }

    if (payment.status !== 'paid') {
      return new Response(JSON.stringify({ error: 'Payment not yet confirmed' }), { status: 422 });
    }

    const { rental } = payment as typeof payment & {
      rental: {
        property: { name: string; address_line1: string; city: string; state: string };
        landlord: { full_name: string; pan_number?: string };
        tenant: { full_name: string; pan_number?: string };
      };
    };

    const receiptNo = `FLV-${payment.id.slice(0, 8).toUpperCase()}`;
    const month = new Date(payment.month).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
    const paidAt = new Date(payment.paid_at!).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
    const address = `${rental.property.name}, ${rental.property.address_line1}, ${rental.property.city}, ${rental.property.state}`;

    const html = buildReceiptHtml({
      tenantName: rental.tenant.full_name,
      tenantPan: rental.tenant.pan_number,
      landlordName: rental.landlord.full_name,
      landlordPan: rental.landlord.pan_number,
      propertyAddress: address,
      month,
      amount: payment.amount,
      receiptNo,
      paidAt,
    });

    // Store HTML as receipt in storage
    const fileName = `receipts/${payment.rental_id}/${payment.id}.html`;
    const { error: uploadError } = await supabase.storage
      .from('agreements')
      .upload(fileName, new TextEncoder().encode(html), {
        contentType: 'text/html',
        upsert: true,
      });

    if (uploadError) {
      console.error('Receipt upload error:', uploadError);
    } else {
      const { data: urlData } = supabase.storage.from('agreements').getPublicUrl(fileName);
      await supabase
        .from('rent_payments')
        .update({ receipt_url: urlData.publicUrl })
        .eq('id', paymentId);
    }

    return new Response(html, {
      status: 200,
      headers: { 'Content-Type': 'text/html' },
    });
  } catch (err) {
    console.error('generate-hra-receipt error:', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
});
