import type { Metadata } from 'next'
import { MarketingNav, MarketingFooter } from '@/components/marketing-shell'

export const metadata: Metadata = {
  title: 'Free HRA Rent Receipt Generator India — RentyBase',
  description: 'Generate Section 10(13A)-compliant HRA rent receipts instantly. Free online tool for Indian tenants and landlords. Download as PDF, valid for income tax exemption.',
  alternates: { canonical: 'https://rentybase.com/tools' },
  openGraph: {
    title: 'Free HRA Rent Receipt Generator India — RentyBase',
    description: 'Generate valid HRA rent receipts in seconds. Free, no sign-up required for the basic generator.',
    url: 'https://rentybase.com/tools',
  },
}

const tools = [
  {
    icon: '📄',
    tag: 'MOST POPULAR',
    title: 'HRA Rent Receipt Generator',
    body: 'Generate a Section 10(13A)-compliant rent receipt in seconds. Enter tenant name, landlord PAN, rent amount, period, and address — download as PDF immediately.',
    cta: 'Generate receipt',
    href: '/signup',
  },
  {
    icon: '📊',
    tag: 'LANDLORDS',
    title: 'Rent Ledger',
    body: 'Log every payment — UPI, NEFT, cash — with date, UTR number, and method. Both landlord and tenant see the same record. Overdue alerts on due date.',
    cta: 'Start tracking',
    href: '/signup',
  },
  {
    icon: '📸',
    tag: 'MOVE-IN / MOVE-OUT',
    title: 'Photo Proof Vault',
    body: 'Upload room photos at move-in. Each photo gets a timestamp, geotag, and cryptographic seal. Neither side can alter them. Permanent and tamper-proof.',
    cta: 'Upload proof',
    href: '/signup',
  },
  {
    icon: '🔒',
    tag: 'DEPOSITS',
    title: 'Deposit Calculator & Ledger',
    body: 'Track the full deposit lifecycle — received, deductions with written reasons, and final refund. Both parties have a permanent record of every rupee.',
    cta: 'Track deposit',
    href: '/signup',
  },
]

const faqs = [
  {
    q: 'Is the HRA receipt legally valid?',
    a: 'Yes. Receipts generated by RentyBase meet the requirements of Section 10(13A) of the Income Tax Act. They include all mandatory fields: tenant name, landlord name and PAN, rent amount, rental period, and property address.',
  },
  {
    q: 'Do I need my landlord\'s PAN number?',
    a: 'Your landlord\'s PAN is required if your annual rent exceeds ₹1 lakh (i.e., monthly rent above ~₹8,333). For rent below this threshold, PAN is optional but recommended.',
  },
  {
    q: 'Can I download receipts for a full financial year?',
    a: 'Yes. RentyBase lets you download individual monthly receipts or a bundled PDF for the full financial year in one click — ready to submit to your employer.',
  },
  {
    q: 'Is RentyBase free?',
    a: 'Every feature — rent ledger, HRA receipts, deposit tracking, move-in proof, and repair tracking — is free for both landlords and tenants. No subscription, no credit card.',
  },
]

export default function ToolsPage() {
  return (
    <div className="lp-page">
      <MarketingNav />

      {/* Hero */}
      <section style={{ paddingTop: 120, paddingBottom: 80, background: 'var(--rb-canvas-2)', borderBottom: '1px solid var(--rb-border)' }}>
        <div className="container" style={{ maxWidth: 800, textAlign: 'center' }}>
          <div className="eyebrow" style={{ marginBottom: 16 }}>FREE TOOLS</div>
          <h1 style={{ fontFamily: 'var(--rb-font-display)', fontSize: 'clamp(36px,6vw,58px)', fontWeight: 400, lineHeight: 1.04, letterSpacing: '-.03em', marginBottom: 20 }}>
            Everything a rental needs,<br /><em style={{ fontStyle: 'italic', color: 'var(--rb-action)' }}>free forever.</em>
          </h1>
          <p style={{ fontSize: 18, lineHeight: 1.65, color: 'var(--rb-ink-2)', maxWidth: 560, margin: '0 auto 36px' }}>
            HRA receipt generator, rent ledger, deposit tracker, and move-in proof vault — all in one place. No credit card. No subscription.
          </p>
          <a href="/signup" className="btn btn-primary" style={{ padding: '12px 24px', fontSize: 15 }}>Start free — no card needed</a>
        </div>
      </section>

      {/* Tools grid */}
      <section style={{ padding: '80px 0', background: 'var(--rb-canvas)' }}>
        <div className="container">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))', gap: 24 }}>
            {tools.map(t => (
              <div key={t.title} style={{ background: 'var(--rb-surface)', border: '1px solid var(--rb-border)', borderRadius: 20, padding: '32px 32px 36px', display: 'flex', flexDirection: 'column' }}>
                <div style={{ fontSize: 32, marginBottom: 16 }}>{t.icon}</div>
                <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--rb-accent)', marginBottom: 10 }}>{t.tag}</div>
                <h2 style={{ fontFamily: 'var(--rb-font-sans)', fontSize: 19, fontWeight: 600, marginBottom: 12, color: 'var(--rb-ink)', lineHeight: 1.3 }}>{t.title}</h2>
                <p style={{ fontSize: 14, lineHeight: 1.7, color: 'var(--rb-ink-2)', flex: 1, marginBottom: 24 }}>{t.body}</p>
                <a href={t.href} className="btn btn-primary" style={{ padding: '10px 20px', fontSize: 14, alignSelf: 'flex-start' }}>{t.cta} →</a>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* HRA explainer */}
      <section style={{ padding: '80px 0', background: 'linear-gradient(160deg,#0F4C5C 0%,#0E1413 100%)', color: '#F6F4EE' }}>
        <div className="container" style={{ maxWidth: 760 }}>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '.14em', textTransform: 'uppercase', color: 'rgba(201,122,58,.9)', marginBottom: 16 }}>HRA RECEIPTS EXPLAINED</div>
          <h2 style={{ fontFamily: 'var(--rb-font-display)', fontSize: 'clamp(28px,4vw,42px)', fontWeight: 400, lineHeight: 1.06, letterSpacing: '-.025em', marginBottom: 20 }}>
            What makes a rent receipt legally valid for HRA?
          </h2>
          <p style={{ fontSize: 16, lineHeight: 1.65, color: 'rgba(246,244,238,.75)', marginBottom: 32 }}>
            Under Section 10(13A) of the Income Tax Act, a rent receipt must include: tenant's full name, landlord's full name and PAN (if annual rent exceeds ₹1 lakh), the monthly rent amount, the rental period it covers, and the full rental property address. RentyBase auto-fills every field from your rental profile.
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(160px,1fr))', gap: 24 }}>
            {[
              ['Section 10(13A)', 'Legally compliant'],
              ['Landlord PAN', 'Auto-filled'],
              ['PDF format', 'Instant download'],
              ['Yearly bundle', 'One-click export'],
            ].map(([k, v]) => (
              <div key={k} style={{ borderTop: '1px solid rgba(246,244,238,.15)', paddingTop: 16 }}>
                <div style={{ fontFamily: 'var(--rb-font-mono)', fontSize: 10, fontWeight: 700, letterSpacing: '.12em', color: 'rgba(201,122,58,.8)', textTransform: 'uppercase', marginBottom: 6 }}>{k}</div>
                <div style={{ fontSize: 15, fontWeight: 600, color: '#F6F4EE' }}>{v}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section style={{ padding: '80px 0', background: 'var(--rb-canvas)' }}>
        <div className="container" style={{ maxWidth: 720 }}>
          <div style={{ textAlign: 'center', marginBottom: 56 }}>
            <div className="eyebrow" style={{ marginBottom: 12 }}>FAQ</div>
            <h2 style={{ fontFamily: 'var(--rb-font-display)', fontSize: 'clamp(26px,4vw,38px)', fontWeight: 400, letterSpacing: '-.025em' }}>Common questions</h2>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
            {faqs.map((f, i) => (
              <div key={f.q} style={{ padding: '28px 0', borderTop: i === 0 ? 'none' : '1px solid var(--rb-border)' }}>
                <h3 style={{ fontFamily: 'var(--rb-font-sans)', fontSize: 16, fontWeight: 600, marginBottom: 10, color: 'var(--rb-ink)' }}>{f.q}</h3>
                <p style={{ fontSize: 14, lineHeight: 1.7, color: 'var(--rb-ink-2)' }}>{f.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section style={{ padding: '80px 32px', textAlign: 'center', background: 'var(--rb-canvas-2)', borderTop: '1px solid var(--rb-border)' }}>
        <div className="eyebrow" style={{ marginBottom: 16 }}>FREE · NO CARD NEEDED</div>
        <h2 style={{ fontFamily: 'var(--rb-font-display)', fontSize: 'clamp(28px,4vw,44px)', fontWeight: 400, letterSpacing: '-.025em', marginBottom: 16 }}>
          Generate your first receipt now.
        </h2>
        <p style={{ fontSize: 16, color: 'var(--rb-ink-2)', marginBottom: 32, maxWidth: 440, marginLeft: 'auto', marginRight: 'auto', lineHeight: 1.6 }}>
          Sign up free and generate Section 10(13A)-valid HRA receipts for every month — automatically, the moment rent is logged.
        </p>
        <a href="/signup" className="btn btn-primary" style={{ padding: '13px 28px', fontSize: 16 }}>Start free</a>
      </section>

      <MarketingFooter />
    </div>
  )
}
